from docx import Document
import os

TEMPLATES_DIR = os.path.join(os.path.dirname(__file__), "templates")
os.makedirs(TEMPLATES_DIR, exist_ok=True)

# 1. NDA Template
nda = Document()
nda.add_heading("NON-DISCLOSURE AGREEMENT", 0)
nda.add_paragraph("This Non-Disclosure Agreement (this \"Agreement\") is entered into on {{ effective_date }}, by and between:")
nda.add_paragraph("1. {{ disclosing_party_name }} (\"Disclosing Party\"), and")
nda.add_paragraph("2. {{ receiving_party_name }} (\"Receiving Party\").")
nda.add_heading("1. Purpose", level=1)
nda.add_paragraph("The Receiving Party understands that the Disclosing Party has disclosed or may disclose information relating to: {{ purpose }}, which to the extent previously, presently, or subsequently disclosed to the Receiving Party is hereinafter referred to as \"Proprietary Information\" of the Disclosing Party.")
nda.add_heading("2. Duration", level=1)
nda.add_paragraph("The obligations of confidentiality shall remain in effect for a period of {{ duration_years }} years from the Effective Date.")
nda.add_heading("3. Jurisdiction", level=1)
nda.add_paragraph("This Agreement shall be governed by the laws of {{ jurisdiction_state }}.")
nda.add_paragraph("\nIN WITNESS WHEREOF, the parties have executed this Agreement as of the date first above written.\n\n_______________________\nDisclosing Party\n\n_______________________\nReceiving Party")
nda.save(os.path.join(TEMPLATES_DIR, "nda_template.docx"))

# 2. Rental Agreement Template
rental = Document()
rental.add_heading("RESIDENTIAL RENTAL AGREEMENT", 0)
rental.add_paragraph("This Rental Agreement is made and executed on {{ start_date }} by and between:")
rental.add_paragraph("LANDLORD: {{ landlord_name }}")
rental.add_paragraph("TENANT: {{ tenant_name }}")
rental.add_heading("1. Property Address", level=1)
rental.add_paragraph("The Landlord agrees to let out and the Tenant agrees to take on rent the property situated at:\n{{ property_address }}")
rental.add_heading("2. Rent and Deposit", level=1)
rental.add_paragraph("The Tenant shall pay a monthly rent of ₹ {{ rent_amount }} to the Landlord.")
rental.add_paragraph("The Tenant has paid a security deposit of ₹ {{ security_deposit }}, which shall be refunded at the time of vacating the premises, subject to lawful deductions for unpaid rent or actual damages beyond normal wear and tear.")
rental.add_heading("3. Duration", level=1)
rental.add_paragraph("This agreement is valid for a period of {{ duration_months }} months starting from {{ start_date }}.")
rental.add_paragraph("\nIN WITNESS WHEREOF, the parties hereto have set their hands on the day and year first above written.\n\n_______________________\nLandlord\n\n_______________________\nTenant\n\nWitness 1: __________________\nWitness 2: __________________")
rental.save(os.path.join(TEMPLATES_DIR, "rental_agreement_template.docx"))

# 3. General Affidavit Template
affidavit = Document()
affidavit.add_heading("GENERAL AFFIDAVIT", 0)
affidavit.add_paragraph("BEFORE THE EXECUTIVE MAGISTRATE / NOTARY PUBLIC")
affidavit.add_paragraph("I, {{ deponent_name }}, son/daughter/wife of {{ father_name }}, aged about {{ age }} years, residing at {{ address }}, do hereby solemnly affirm and declare on oath as under:")
affidavit.add_heading("1. Statement of Facts", level=1)
affidavit.add_paragraph("{{ statement }}")
affidavit.add_heading("2. Verification", level=1)
affidavit.add_paragraph("I, the above named deponent, do hereby verify that the contents of this affidavit are true and correct to the best of my knowledge and belief, and no part of it is false.")
affidavit.add_paragraph("Solemnly affirmed at on this {{ date }}.\n\n_______________________\nDEPONENT")
affidavit.save(os.path.join(TEMPLATES_DIR, "general_affidavit_template.docx"))

# 4. FIR Draft Template
fir = Document()
fir.add_heading("FIRST INFORMATION REPORT (DRAFT)", 0)
fir.add_paragraph("To,\nThe Station House Officer (S.H.O),\nPolice Station: {{ police_station }},\nCity/District: {{ city }}")
fir.add_paragraph("SUBJECT: Complaint Regarding Incident Occurred on {{ incident_date }}")
fir.add_paragraph("Sir/Madam,\nI, {{ complainant_name }}, resident of the aforementioned district, wish to lodge this formal report regarding the following incident:")
fir.add_heading("1. Details of Incident", level=1)
fir.add_paragraph("{{ incident_details }}")
fir.add_heading("2. Suspect Details (if known)", level=1)
fir.add_paragraph("{{ suspect_details }}")
fir.add_paragraph("I request you to register a formal FIR and initiate an immediate investigation under the applicable provisions of the Bharatiya Nagarik Suraksha Sanhita (BNSS) and Bharatiya Nyaya Sanhita (BNS).\n\nYours faithfully,\n\n_______________________\n{{ complainant_name }}")
fir.save(os.path.join(TEMPLATES_DIR, "fir_draft_template.docx"))

# 5. Legal Notice Template
notice = Document()
notice.add_heading("LEGAL NOTICE", 0)
notice.add_paragraph("BY REGISTERED POST A.D. / SPEED POST")
notice.add_paragraph("To,\n{{ recipient_name }},\n{{ recipient_address }}")
notice.add_paragraph("SUBJECT: {{ subject }}")
notice.add_paragraph("Under instructions from and on behalf of my client {{ sender_name }}, I hereby serve you with this formal Legal Notice:")
notice.add_heading("1. Statement of Grievance & Facts", level=1)
notice.add_paragraph("{{ notice_body }}")
notice.add_heading("2. Demand for Action", level=1)
notice.add_paragraph("You are hereby called upon to comply with the following demands: {{ demand }}, within {{ deadline_days }} days from the date of receipt of this notice.")
notice.add_paragraph("Take notice that if you fail to comply, my client shall be constrained to initiate appropriate civil and criminal legal proceedings against you at your sole risk and cost.\n\nYours faithfully,\n\n_______________________\nAdvocate / Sender")
notice.save(os.path.join(TEMPLATES_DIR, "legal_notice_template.docx"))

# 6. Power of Attorney Template
poa = Document()
poa.add_heading("GENERAL POWER OF ATTORNEY", 0)
poa.add_paragraph("KNOW ALL MEN BY THESE PRESENTS that I, {{ principal_name }}, residing at {{ principal_address }} (\"Principal\"), do hereby nominate, constitute and appoint {{ agent_name }}, residing at {{ agent_address }} (\"Agent/Attorney\"), to be my true and lawful attorney in my name and on my behalf to do and execute all acts and deeds.")
poa.add_paragraph("This Power of Attorney shall take effect from {{ effective_date }}.")
poa.add_paragraph("\nIN WITNESS WHEREOF, I have executed this Power of Attorney.\n\n_______________________\nPrincipal\n\n_______________________\nAgent Acceptance\n\nWitness 1: __________________\nWitness 2: __________________")
poa.save(os.path.join(TEMPLATES_DIR, "power_of_attorney_template.docx"))

# 7. Will Template
will = Document()
will.add_heading("LAST WILL AND TESTAMENT", 0)
will.add_paragraph("I, {{ testator_name }}, residing at {{ testator_address }}, of sound mind and memory, do hereby make, publish, and declare this as my Last Will and Testament, hereby revoking all prior Wills.")
will.add_heading("1. Appointment of Executor", level=1)
will.add_paragraph("I hereby appoint {{ executor_name }} to be the Executor of this my Last Will and Testament.")
will.add_heading("2. Bequests and Distribution of Assets", level=1)
will.add_paragraph("{{ beneficiary_details }}")
will.add_paragraph("Signed by the Testator on {{ date }} in the presence of two witnesses.\n\n_______________________\nTestator Signature\n\nWitness 1: __________________\nWitness 2: __________________")
will.save(os.path.join(TEMPLATES_DIR, "will_template.docx"))

# 8. Employment Agreement Template
emp = Document()
emp.add_heading("EMPLOYMENT AGREEMENT", 0)
emp.add_paragraph("This Employment Agreement is entered into between {{ employer_name }} (\"Employer\") and {{ employee_name }} (\"Employee\").")
emp.add_heading("1. Position and Commencement", level=1)
emp.add_paragraph("The Employee is hired for the position of {{ job_title }}, commencing on {{ start_date }}.")
emp.add_heading("2. Remuneration", level=1)
emp.add_paragraph("The Employee shall receive a monthly gross salary of ₹ {{ salary }}.")
emp.add_heading("3. Termination & Notice Period", level=1)
emp.add_paragraph("Either party may terminate this employment by providing {{ notice_period }} month(s) written notice or salary in lieu thereof.")
emp.add_paragraph("\nIN WITNESS WHEREOF, the parties hereto have executed this Agreement.\n\n_______________________\nEmployer\n\n_______________________\nEmployee")
emp.save(os.path.join(TEMPLATES_DIR, "employment_agreement_template.docx"))

print("All 8 templates created successfully.")
